sudo: false
language: node_js
node_js:
- "4.9.1"
branches:
  only:
  - master
  - develop
env:
  global:
  # GPG_KEY
  - secure: "ttZI6afay+AhfLG7LR0StJziNyIysYfddDpvO7hLEmaR0tbf1+Bnb6Xvil0G3/aUcjhPl4La8l+9nPW/sCB19EKOaCnq3GYqKwFTg81Yjv7/EnHxwp4UGntemRY8pEC5dl39Qh6D0mgXJ+rnTpLK9zf+qtnNfp4JAy+5evnFfTuI/bh2GykG6tiPjVCZeCT29FQv0ft3Irb87rj7VvCGFzFPnOFY+sXzH6MB07hxJFILAHpwUBcGG98lE8ZmDgT2hZ4Dqwd/lhkFQjcgnPDSVGGi+n40yGGYnxgg5oGtJIfdKABT3DAJ1/8+vQkAbLBL9g9dYKFw+JT29yBe77WTa8aOWBdd3EC1LnckkpjbkKcfBZcdoMh089/R1DE0VSzxhLbWrnRrgBoOYjysFc/ct+ymhJ9Y4Worczjwx5qg2jWkB9/rnzqYucggA2RMJW5iKe5h3/+U+qkU5XkwKCH/AqsB+YbB5gpEaVgvmyUApjatErPtUsJt8Ylzhh2i0gNCQslR5XWEReKLd0L0cApfhMMZ+7xFJ1ko0qYyJRtw8Ed5LXBFZv/HKPhxd6baN0gq0+6nSWqtApsIONSEbvJVPzkNpjVFZ5HGZ33meR0RrUrJSmp7RFtmuQ2aghO4zIOtacyqUCCMyx0KI7fGjZMVwrlpApN35TRymJZZtk/OukU="
before_install:
- npm install -g grunt-cli
- npm install -g bower
- bower install
script: grunt
after_script: bash travis.sh
